version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: postgis_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: map_route_dtb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi_app:
    build: .
    container_name: fastapi_pathfinding
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:123456@postgres:5432/map_route_dtb
      WEATHER_API_KEY: d4b84d495c4303582c5835a354d9b3c9
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: