services:
  # Service 1: PostGIS Database
  postgres:
    image: postgis/postgis:15-3.3
    container_name: postgis_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Service 2: Database initialization (runs once)
  db_init:
    build: .
    container_name: db_initializer
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./cache:/app/cache
    command: python src/database/db_service.py
    restart: "no"

  # Service 3: FastAPI application
  fastapi_app:
    build: .
    container_name: fastapi_pathfinding
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db_init:
        condition: service_completed_successfully
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

volumes:
  postgres_data: